group=cc.skydom.server.chosen
version=1.20.4-R0.1-SNAPSHOT

mcVersion=1.20.4
PaperRef=2fdb2e9dcdfb127cb99134f9bec60dcc2a6954d2

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8 -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true -Dgraal.SpeculativeGuardMovement=true -Dgraal.WriteableCodeCache=true
